"""empty message

Revision ID: 14222a2b6cf5
Revises: 7e5fcfc5a3db
Create Date: 2017-09-08 11:54:04.536182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14222a2b6cf5'
down_revision = '7e5fcfc5a3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
